image: lorisleiva/laravel-docker:8.2

stages:
  - php_build
  - js_build
  - test
  - deploy

composer:
  stage: php_build
  image: composer:2.7.7

  before_script:
    - cd $CI_PROJECT_DIR/web # Navigate to the project directory

  script:
    - composer -v
    - composer install --prefer-dist --no-ansi --no-interaction --no-scripts --ignore-platform-reqs --no-progress
    - ls -la
    - ls -la ..
    # TODO: check where are .env variables
    #- cp .env.example .env
    #- php artisan key:generate

  artifacts:
    expire_in: 1 month
    paths:
      - web/vendor/

  cache:
    # The variable CI_COMMIT_REF_SLUG
    # refers to the slug of the branch.
    # For example: `master` for the master branch.
    # We use the `composer` suffix to avoid conflicts with
    # the `npm` cache that we'll define next.
    key: ${CI_COMMIT_REF_SLUG}-composer

    # Define what to cache.
    paths:
     - web/vendor/

  only:
    - master

npm:
  # Same stage as `composer` so that they run in parallel.
  stage: js_build
  image: node:22.5.1-slim

  dependencies:
    - composer #to be able to have filament tailwind style presets

  before_script:
    - cd $CI_PROJECT_DIR/web # Navigate to the project directory

  # Install and compile.
  script:
    - ls -la
    - ls -la ..
    - node -v
    - npm -v
    - npm install # node_modules
    - npm run build # public/build

  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - web/node_modules/

  artifacts:
    expire_in: 1 month
    paths:
      - web/node_modules/
      - web/public/build
    
  only:
    - master

filament:
  # Same stage as `composer` so that they run in parallel.
  stage: js_build
  image: php:8.2-alpine3.17

  dependencies:
    - composer #to be able to have filament tailwind style presets

  before_script:
    - cd $CI_PROJECT_DIR/web # Navigate to the project directory

  # Install and compile.
  script:
    - php artisan filament:assets

  # Provide the other jobs of the pipeline with
  # the node dependencies and the compiled assets.
  artifacts:
    expire_in: 1 month
    paths:
      - web/public/css/
      - web/public/js/

  only:
    - master

phpunit:
  stage: test

  # List of jobs from which it will download the artifacts.
  #dependencies:
  #  - composer

  script:
    - echo "TODO Running PHPUnit tests"
    #- phpunit --coverage-text --colors=never

codestyle:
  stage: test
  dependencies: []
  script:
    - echo "Running PHP Code Sniffer"
    #- phpcs --standard=PSR2 --extensions=php --ignore=app/Support/helpers.php app

# Add a `.` in front of a job to make it hidden.
# Add a `&reference` to make it a reusable template.
# Note that we don't have dashes anymore.
.init_ssh: &init_ssh |
  command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )
  eval $(ssh-agent -s)
  chmod 400 "$SSH_PRIVATE_KEY"
  ssh-add "$SSH_PRIVATE_KEY"
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh

#ssh-keyscan -H 10.31.10.11 >> ~/.ssh/known_hosts

production:
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PUBLIC_KEY" >> ~/.ssh/id_rsa.pub
    - ls -la ~/.ssh
    - cat ~/.ssh/id_rsa.pub
    - ping -c 1 mdcenter.uni-lj.si
    #- ssh-keyscan 10.31.10.11
    #- cat ~/.ssh/known_hosts
    #- chmod 644 ~/.ssh/known_hosts
  script:
    - echo "connecting to server"
    - echo "run gitlab runner on mdcenter to be able to connect to server"
    #- ssh -vvv -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" root@10.31.10.11 "
    #  whoami &&
    #  docker ps"

  # Do not run automatically.
  # Wait for a human to click on play.
  #when: manual

  #only:
  #  - master

  
