image: lorisleiva/laravel-docker:8.2


stages:
  - build

composer:
  stage: build
  image: composer:2.7.7

  script:
    - composer -v
    - echo "test new"
    #- composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    # TODO: check where are .env variables
    #- cp .env.example .env
    #- php artisan key:generate

  artifacts:
    # (Optional) Give it an expiration date,
    # after that period you won't be able to
    # download them via the UI anymore.
    expire_in: 1 month

    # Define what to output from the job.
    paths:
      - vendor/
      #- .env

  cache:
    # The variable CI_COMMIT_REF_SLUG
    # refers to the slug of the branch.
    # For example: `master` for the master branch.
    # We use the `composer` suffix to avoid conflicts with
    # the `npm` cache that we'll define next.
    key: ${CI_COMMIT_REF_SLUG}-composer

    # Define what to cache.
    paths:
      - vendor/
