version: "3"
services:
    map-php:
        build:
            context: ./mnt/docker
            dockerfile: local.dockerfile
        image: map-php
        container_name: map-php
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./web:/var/www
            - ./mnt/php/local/local.ini:/usr/local/etc/php/conf.d/local.ini
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            XDEBUG_MODE: develop,debug
            XDEBUG_CONFIG:
                client_host=host.docker.internal
                start_with_request=yes

    map-webserver:
        image: nginx:alpine
        container_name: map-webserver
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./web/:/var/www
            - ./mnt/nginx/local:/etc/nginx/conf.d/
        depends_on:
            - map-php

    map-db:
        image: postgres:15-alpine
        container_name: map-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
            TZ: Europe/Ljubljana
        ports:
            - "5432:5432"
        volumes:
            - map_db_data:/var/lib/postgresql/data

    map-redis:
        image: redis:alpine
        container_name: map-redis
        restart: unless-stopped
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - "6379:6379"
        volumes:
            - map_redis_data:/data

    mailhog:
        image: mailhog/mailhog
        ports:
        - 1025:1025 # smtp server
        - 8025:8025 # web ui

    map-adminer:
        image: adminer
        container_name: map-adminer
        restart: unless-stopped
        ports:
            - 8080:8080

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: dev@agiledrop.com
            PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5050:80"
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            - map-db

volumes:
    map_db_data:
        driver: local
    map_redis_data:
        driver: local
    pgadmin_data:
        driver: local