version: "3"
services:
    map-php:
        build:
            context: ./mnt/docker
            dockerfile: Dockerfile
        image: map-php
        container_name: map-php
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./web:/var/www
            - ./mnt/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    map-webserver:
        image: nginx:alpine
        container_name: map-webserver
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./web/:/var/www
            - ./mnt/nginx/prod:/etc/nginx/conf.d/
            - /etc/ssl/certs/ssl-cert-snakeoil.pem:/etc/nginx/ssl/ssl-cert-snakeoil.pem
            - /etc/ssl/private/ssl-cert-snakeoil.key:/etc/nginx/ssl/ssl-cert-snakeoil.key
        depends_on:
            - map-php
        links:
            - map-php

    map-db:
        image: postgres:15-alpine
        container_name: map-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - map_db_data:/var/lib/postgresql/data

    map-redis:
        image: redis:alpine
        container_name: map-redis
        restart: unless-stopped
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - "6379:6379"
        volumes:
            - map_redis_data:/data

volumes:
    map_db_data:
        driver: local
    map_redis_data:
        driver: local